// <auto-generated />
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ETG.SABENTISpro.Models.Core.Locale
{

    // CORE_LOCALES_SOURCE
    [Table("CORE_LOCALES_SOURCE", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.0.0")]
    public partial class CORE_LOCALES_SOURCE
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"id", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_CORE_LOCALES_SOURCE_1", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public System.Guid id { get; set; } // id (Primary key)

        [Column(@"source", Order = 2, TypeName = "nvarchar")]
        [Required]
        [Display(Name = "Source")]
        public string source { get; set; } // source

        [Column(@"cacheStrategy", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Cache strategy")]
        public int cacheStrategy { get; set; } // cacheStrategy

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Column(@"length", Order = 4, TypeName = "bigint")]
        [Display(Name = "Length")]
        public long? length { get; private set; } // length

        public CORE_LOCALES_SOURCE()
        {
            cacheStrategy = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}