// <auto-generated />
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ETG.SABENTISpro.Models.Core.Locale
{

    // CORE_LOCALES_SOURCE
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.0.0")]
    public partial class CORE_LOCALES_SOURCEConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CORE_LOCALES_SOURCE>
    {
        public CORE_LOCALES_SOURCEConfiguration()
            : this("dbo")
        {
        }

        public CORE_LOCALES_SOURCEConfiguration(string schema)
        {
            Property(x => x.length).IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}